### ISSUE TITLE
No need for worldTransform

### ISSUE THREAD

**Issue by Askhento** [aferriss/spark-ar-lookat-example#1]
If you will rotate the camera lookAt will not work properly in your example.
To fix it just put everything in the same hierarchy (ex. Focal Distance) and use only transform signals.

**Comment by aferriss** [comment]
Thanks for the suggestion! closing with https://github.com/aferriss/spark-ar-lookat-example/commit/730905067ae3f8f26e1409c24608307429ae55c8
