### ISSUE TITLE
 Look At in Spark AR - Not working as expected

### ISSUE THREAD

**Issue by paka3d** [aferriss/spark-ar-lookat-example#2]
Hi Adam,

Thanks again for providing this great example on here. I've been looking into using this example with Spark AR's camera. Although, when I try grouping the follow object to the camera, the target no longer functions correctly.  Could you suggest a strategy I could use that would allow a 3d object in world space to face the camera at all times.  

Thank you so much for your time.

-Pascal

**Comment by aferriss** [comment]
Hi there,

this is actually an with sparks implementation. I think the lookat and the follow need to be in the same camera space in order for this to work. I think there might be a solve for doing what you're asking but it's probably a more complex solve that doesn't rely on a builtin spark function.

**Comment by paka3d** [comment]
Thanks for the quick response!

 I figured something a little more sophisticated would be needed.  Since the camera in Spark AR does not expose any transforms in the editor or with any of the patches,  In Unity this is referred to as a billboard effect and works great with just 2d images on a plane ( a tree for example ) where ever the camera is the tree billboards would just rotate to face the camera. I do have some JavaScript knowledge but it's mostly geared towards Unity development. Could you suggest what next steps could be. 

Thanks again for taking the time.

-Pascal

**Comment by aferriss** [comment]
There's a couple different ways to billboard. You might look into using a patch asset material (which gives you access to the vertex shader) and implementing something like this https://www.geeks3d.com/20140807/billboarding-vertex-shader-glsl/ or this https://stackoverflow.com/questions/41767490/how-to-transform-vertices-in-vertex-shader-to-get-a-3d-billboard

**Comment by aferriss** [comment]
I think something like this might work for you.
![Screen Shot 2020-06-16 at 4 15 45 PM](https://user-images.githubusercontent.com/3698659/84837537-3d5f7f00-afed-11ea-9bd4-f7a0edf8eca7.png)

**Comment by paka3d** [comment]
Thank you Adam!

 Just knowing the effect is actually possible in Spark AR is reassuring and has given me hope. Thanks again for your time and expertise. I'll give it a try!

-Pascal

**Comment by NeoHoffa** [comment]
@aferriss  @paka3d,

I came across the `lookAt()` method here (scroll down) : https://sparkar.facebook.com/ar-studio/learn/documentation/reference/classes/scenemodule.transform/

Would this work? And how?

**Comment by aferriss** [comment]
@NeoHoffa that's exactly the method that this example shows in use. You can see it being called here https://github.com/aferriss/spark-ar-lookat-example/blob/master/lookAtExample/scripts/script.js#L35

It's possible things have changed a bit since I made this but I think the usage is probably pretty much the same

**Comment by NeoHoffa** [comment]
Yeah, I can't seem to find a solution for this either. @aferriss, any way you can add an example for an object to always face the camera itself? 

I see that SparkAR has billboarding support in their particle system. Funny that its not a default feature.

**Comment by JoebRogers** [comment]
@aferriss Just wondering if you could elaborate a little on the vertex example you posted up above, as I'm also trying to setup camera billboarding with little success (for world space canvases). What is the `Position` node you're passing the result into? I'd thought it was a Vector4 variable being bridged into script, but in trying that I get a "Patch received input of type `Vector4`, when the expected type was `ShaderGeneric`". 

I assume I'm missing something obvious as to where this vertex example should be input to my billboarding object. I apologise if this is an obvious question, my SparkAR related Google-fu has failed me however, so additional information would be much appreciated!

**Comment by aferriss** [comment]
@JoebRogers The position node is one of the outputs from a `Patch Asset Material`. It represents `gl_Position` in what is normally a vertex shader. 

![Screen Shot 2020-07-13 at 4 25 17 PM](https://user-images.githubusercontent.com/3698659/87363190-7e33b080-c525-11ea-9e4c-9f1f9c4c1d79.png)

**Comment by JoebRogers** [comment]
@aferriss Thanks for the quick response, haven't messed much with patch asset shaders, so that explains a lot! It didn't work, and ended up exploding the entire scene output lol, but I'll play around with it a bit and see what I can come up with. Thanks!
